hw09_struct_validator is compleated
trb1maker/otus_golang_home_work pull request #16
Opened 2024-05-01 16:58 UTC by trb1maker

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-05-05 08:00 UTC, dshemin requested changes

2024-05-05 08:00 UTC, dshemin commented on hw09_struct_validator/validator.go
> +func isValidationError(err error) bool {
Важно:

Лучшен создать отдельный тип ошибок и проверять через errors.As

2024-05-05 10:31 UTC, trb1maker commented on hw09_struct_validator/validator.go
> +func isValidationError(err error) bool {
Реализовал тип в пакете rules, проверяю с помощью errors.As.

2024-05-05 10:31 UTC, trb1maker commented on hw09_struct_validator/validator.go
> +		t := v.Type().Field(i)
Исправил.

2024-05-11 08:44 UTC, dshemin approved these changes

2024-05-11 10:54 UTC, merged