hw12_calendar
trb1maker/otus_golang_home_work pull request #21
Opened 2024-05-19 17:42 UTC by trb1maker

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2024-05-22 05:28 UTC, dshemin requested changes

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +	if err := os.Setenv("SERVERHOST", h.Host); err != nil {
Важно:

Зачем мы устанавливаем переменные окружения?

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) DeleteEvent(ctx context.Context, eventID string) error {
Критично:

Согласно заданию, сейчас надо заложить все метод работы с событиями.
Код приложения, именно его бизнес логика, не должен зависить от того, как и где он вызывается.

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/middleware_test.go
> +		require.True(t, regexp.MustCompile(pattern).MatchString(buf.String()))
Важно:

Есть https://pkg.go.dev/github.com/stretchr/testify/require#Regexp

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	host, ok := os.LookupEnv("SERVERHOST")
Важно:

Передайте уже собранную конфигурацию сюда. Использовать переменные окружения по всему коду - приведёт к сложному рефакторингу в будущем.

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.srv.Addr = host + ":" + port
Важно:

Надо использовать функцию https://pkg.go.dev/net#JoinHostPort. Ваш код приведёт к ошибке если host будет содержать ipv6 адрес

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.srv.Addr = host + ":" + port
Важно:

Более того, желательно чтобы конструктор типа всегда создавал его полностью готовым к использованию. Иными словами - всё это должно быть в NewServer. Кроме ListenAndServe

2024-05-22 05:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +func (s *Storage) DeleteOne(_ context.Context, eventID string) error {
Критично:

Нет всех нужных методов.

2024-05-22 19:45 UTC, trb1maker commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) DeleteEvent(ctx context.Context, eventID string) error {
Иначе говоря: методы приложения должны оперировать только структурами? Правильно я понимаю, что это в дальнейшем важно для интерфейса GRPC? Нет проблем этот метод переписать, просто для удаления достаточно передать идентификатор события, поэтому мне нужно понять, в чем конкретно здесь проблема.

2024-05-22 19:46 UTC, trb1maker commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.srv.Addr = host + ":" + port
+

2024-05-23 05:44 UTC, dshemin requested changes

2024-05-23 05:44 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) DeleteEvent(ctx context.Context, eventID string) error {
Проблема в том что у нас нет методов из задания https://github.com/OtusGolang/home_work/blob/master/hw12_13_14_15_calendar/docs/CALENDAR.MD

```
получить список событий на день/неделю/месяц
```

2024-05-23 06:01 UTC, trb1maker commented on hw12_13_14_15_calendar/internal/app/app.go
> +func (a *App) DeleteEvent(ctx context.Context, eventID string) error {
Это не проблема, сейчас запилю.

2024-05-24 05:02 UTC, dshemin approved these changes

2024-05-24 06:09 UTC, merged