Hw13 calendar
trb1maker/otus_golang_home_work pull request #23
Opened 2024-06-02 08:14 UTC by trb1maker

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-03 06:35 UTC, dshemin requested changes

2024-06-03 06:35 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +generate:
Критично:

Обратите внимание на текст задания:
```
добавить в Makefile команду `generate`; `make generate` - вызывает `go generate`, которая в свою очередь
генерирует код GRPC сервера на основе Protobuf спецификаций;
```

2024-06-03 06:35 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +    string eventId = 2;
Важно:

Данное сообщение используется для многих методов. Включая получения списка. В них точно используются поля eventId и event? Лучше разбивать сообщения запросов и ответов так, чтобы там была только та информация - которая действительно нужна. Мы жу тут формализуем наше АПИ.

2024-06-03 06:35 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		if err := httpServer.Stop(ctx); err != nil {
Важно:

Нет остановки gRPC сервера

2024-06-03 06:35 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +message Response {
Важно:

Тут тоже замечание что и для сообщения Request. Разбейте.

2024-06-03 06:35 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server_test.go
> +	go func() {
Важно:

Этот код не обьязательно запускать в горутине.

2024-06-06 06:23 UTC, dshemin requested changes

2024-06-06 06:23 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +    rpc next(UserRequest) returns (EventResponse);
Критично:

Обратите внимание на ТЗ https://github.com/OtusGolang/home_work/blob/master/hw12_13_14_15_calendar/docs/CALENDAR.MD

```
СписокСобытийНаДень (дата);
СписокСобытийНаНеделю (дата начала недели);
СписокСобытийНaМесяц (дата начала месяца).
```

Нам нужно указать дату за которую мы получаем информацию.

2024-06-06 15:38 UTC, trb1maker commented on hw12_13_14_15_calendar/api/EventService.proto
> +    rpc next(UserRequest) returns (EventResponse);
Добавил дополнительные методы для серверов. Единственный момент: пришлось отключить линтеры, т.к. методы отличаются только вызываемым методом приложения. Можно было бы решить эту проблему, переписав методы HTTP-сервера (запрашиваемый период положить не в путь, а в параметр), но делать этого не хотелось.

2024-06-07 00:17 UTC, dshemin approved these changes

2024-06-07 02:35 UTC, merged